In [3]:
# 1
#parent-person,method-greet,prints-'hello from person'
#child-student,method-study,prints-'student is studying'
#call both method using student object

class person:
    def __init__(self,greet):
        self.greet=greet
        print("hello from person")

class student(person):
    def __init__(self,studt):
        super().__init__()
        self.study=study
        print("student is studying")

In [2]:
# 2
#reverse string
s="wafa"
my_str=""
if len(s)>0:
    i=len(s)-1
while i>=0:
    my_str+=s[i]
    i-=1
print(my_str)

afaw

In [11]:
#
#create dataframe dictionary
import pandas as pd
emp={'name':['alice','bob','charlie'],
'age':[25,30,35],
'city':['delhi','mumbai','bengaluru']}
df=pd.DataFrame(emp)
print(df)

      name  age       city
0    alice   25      delhi
1      bob   30     mumbai
2  charlie   35  bengaluru

In [13]:
#select name column
df.name

0      alice
1        bob
2    charlie
Name: name, dtype: object

In [14]:
#select name and city column
df[['name','city']]

      name       city
0    alice      delhi
1      bob     mumbai
2  charlie  bengaluru

In [16]:
#age>30
df[df.age>30]

      name  age       city
2  charlie   35  bengaluru

In [18]:
#adding new column
df['salary']=50000,60000,70000
print(df)

      name  age       city  salary
0    alice   25      delhi   50000
1      bob   30     mumbai   60000
2  charlie   35  bengaluru   70000

In [19]:
#calculate average salary
df.salary.mean()

np.float64(60000.0)